[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000

remappings = [
  'forge-std/=lib/forge-std/src',
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
]